USE [master]
GO

/****** Object:  Database [InnoTym]    Script Date: 16-10-2019 12:42:16 ******/
CREATE DATABASE [InnoTym]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'InnoTym', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.KRISHNA\MSSQL\DATA\InnoTym.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'InnoTym_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.KRISHNA\MSSQL\DATA\InnoTym_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [InnoTym] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [InnoTym].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [InnoTym] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [InnoTym] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [InnoTym] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [InnoTym] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [InnoTym] SET ARITHABORT OFF 
GO

ALTER DATABASE [InnoTym] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [InnoTym] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [InnoTym] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [InnoTym] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [InnoTym] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [InnoTym] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [InnoTym] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [InnoTym] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [InnoTym] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [InnoTym] SET  ENABLE_BROKER 
GO

ALTER DATABASE [InnoTym] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [InnoTym] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [InnoTym] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [InnoTym] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [InnoTym] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [InnoTym] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [InnoTym] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [InnoTym] SET RECOVERY FULL 
GO

ALTER DATABASE [InnoTym] SET  MULTI_USER 
GO

ALTER DATABASE [InnoTym] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [InnoTym] SET DB_CHAINING OFF 
GO

ALTER DATABASE [InnoTym] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [InnoTym] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [InnoTym] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [InnoTym] SET QUERY_STORE = OFF
GO

ALTER DATABASE [InnoTym] SET  READ_WRITE 
GO

